trigger:
  - master

pool: Default

jobs:
  - job: build_server
    workspace:
      clean: all
    steps:
      - task: DotNetCoreCLI@2
        displayName: dotnet pack
        inputs:
          command: pack
          packagesToPack: '**/JRpcMediator.Server.csproj'
          arguments: '--configuration Release'
      - task: NuGetCommand@2
        displayName: nuget push
        inputs:
          command: 'push'
          packagesToPush: '**/JRpcMediator.Server.*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: '9aa02933-e48e-43d2-b62b-7e53e7cb9e51'
          allowPackageConflicts: true
  - job: build_client
    workspace:
      clean: all
    steps:
      - task: DotNetCoreCLI@2
        displayName: dotnet pack
        inputs:
          command: pack
          packagesToPack: '**/JRpcMediator.Client.csproj'
          arguments: '--configuration Release'
      - task: NuGetCommand@2
        displayName: nuget push
        inputs:
          command: 'push'
          packagesToPush: '**/JRpcMediator.Client.*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: '9aa02933-e48e-43d2-b62b-7e53e7cb9e51'
          allowPackageConflicts: true
  - job: build_web
    workspace:
      clean: all
    steps:
      - powershell: pnpm i
        displayName: pnpm install
        workingDirectory: web
      - powershell: pnpm build
        displayName: pnpm build
        workingDirectory: web
      - task: npmAuthenticate@0
        displayName: npm auth
        inputs:
            workingFile: web/.npmrc
      - powershell: pnpm publish --no-git-checks
        displayName: pnpm publish
        workingDirectory: web